# Header
menu:
  Home: /
  Archives: /archives
  About: about.html
  Github:
    url: https://github.com/victorquan
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: 静静的窝

# URL of the Home page image
index_cover: http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/img/home-bg.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-
  # It is unnecessary to enable disqus here if
  # you have set "disqus_shortname" in your site's "_config.yml"

  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

  # 有言评论系统 www.uyan.cc
  uyan:
    id: 2125856

# Google Analytics Tracking ID
google_analytics:

# baidu Analytics ID add by victor.quan
# 百度统计 http://sitecenter.baidu.com/sc-web/
# 查看代码，填入 //hm.baidu.com/hm.js? 之后的内容
baidu_analytics: 8ca059faeae2d9a8d6316e3e4547dbab

# 排除以下调试ip不统计
isIgnoreSpecialHostVisitor: true
ignoreHostList:
  - localhost
  - 127.0.0.1


# Addthis ID
addthis:

# set your own favicon
favicon: /favicon.ico


# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/victorquan
gitlab_url:
linkedin_url:
#oschina_url: https://my.oschina.net/u/2335354
#v2ex_url: https://www.v2ex.com/member/VictorChaun
#segmentfault_url: https://segmentfault.com/u/ivictorchaun
mailto: