# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Github:
    url: https://github.com/victorquan
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: qzj

# URL of the Home page image
index_cover: /img/shenzhenwan.jpeg

# Default post title
default_post_title: Untitled

# 分享
share: true

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-
  # It is unnecessary to enable disqus here if
  # you have set "disqus_shortname" in your site's "_config.yml"

  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

  # 有言评论系统 www.uyan.cc
  uyan:
    #id: 2125856
    id:

  # 是否开启多说评论，http://duoshuo.com/create-site/
  # 使用上面网址登陆你的多说，然后创建站点，在 domain 中填入你设定的域名前半部分
  # http://<要填的部分>.duoshuo.com (domain只填上<>里的内容，不要填整个网址)
  # 多说将于2017-6-1关闭 详见:http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241
  duoshuo:
    domain:

  # https://github.com/imsun/gitment
  # https://imsun.net/posts/gitment-introduction/
  git_ment:
    owner_id: victorquan
    client_id: 24d1a166f2ff57962706
    client_secret: bdbd5e4b66f0bed78cb7f1993f83537e2e29fd30
    comment_repo: my-blog-comment


# Google Analytics Tracking ID
google_analytics:

# baidu Analytics ID add by victor.quan
# 百度统计 http://sitecenter.baidu.com/sc-web/
# 查看代码，填入 //hm.baidu.com/hm.js? 之后的内容
baidu_analytics: 8ca059faeae2d9a8d6316e3e4547dbab

# 排除以下调试ip不统计
isIgnoreSpecialHostVisitor: true
ignoreHostList:
  - localhost
  - 127.0.0.1


# Addthis ID
addthis:

# set your own favicon
favicon: /favicon.ico


# Social Accounts
twitter_url:
twitter_handle:
facebook_url: https://www.facebook.com/victor.quan.758
github_url: https://github.com/victorquan
gitlab_url:
linkedin_url:
jianshu_url: http://www.jianshu.com/u/97adfad91019
weibo_url: http://weibo.com/u/2115385703
oschina_url: https://my.oschina.net/u/2335354/home
v2ex_url: https://www.v2ex.com/member/VictorChaun
segmentfault_url: https://segmentfault.com/u/ivictorchaun
coding_url: https://coding.net/u/victorquan

#oschina_url: https://my.oschina.net/u/2335354
#v2ex_url: https://www.v2ex.com/member/VictorChaun
#segmentfault_url: https://segmentfault.com/u/ivictorchaun
mailto: